$activeBorderColor = rgba(ff1a1aff) rgba(5c0000ff) 90deg
$inactiveBorderColor = rgba(2a2a2aaa)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
